/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_1bcc1131 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// Uses direct PostgREST fetch — avoids Supabase JS client JWT generation which
// causes "JWT issued at future" errors when the edge runtime clock is skewed.

const TABLE = "kv_store_1bcc1131";
const getUrl = () => `${Deno.env.get("SUPABASE_URL")}/rest/v1/${TABLE}`;
const headers = (): Record<string, string> => ({
  "Content-Type": "application/json",
  "apikey": Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  "Authorization": `Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}`,
});

export const set = async (key: string, value: any): Promise<void> => {
  const res = await fetch(getUrl(), {
    method: "POST",
    headers: { ...headers(), "Prefer": "resolution=merge-duplicates" },
    body: JSON.stringify({ key, value }),
  });
  if (!res.ok) throw new Error(`set failed (${res.status}): ${await res.text()}`);
};

export const get = async (key: string): Promise<any> => {
  const res = await fetch(
    `${getUrl()}?key=eq.${encodeURIComponent(key)}&select=value`,
    { headers: headers() },
  );
  if (!res.ok) throw new Error(`get failed (${res.status}): ${await res.text()}`);
  const data = await res.json();
  return data[0]?.value ?? null;
};

export const del = async (key: string): Promise<void> => {
  const res = await fetch(
    `${getUrl()}?key=eq.${encodeURIComponent(key)}`,
    { method: "DELETE", headers: headers() },
  );
  if (!res.ok) throw new Error(`del failed (${res.status}): ${await res.text()}`);
};

export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const res = await fetch(getUrl(), {
    method: "POST",
    headers: { ...headers(), "Prefer": "resolution=merge-duplicates" },
    body: JSON.stringify(keys.map((k, i) => ({ key: k, value: values[i] }))),
  });
  if (!res.ok) throw new Error(`mset failed (${res.status}): ${await res.text()}`);
};

export const mget = async (keys: string[]): Promise<any[]> => {
  const res = await fetch(
    `${getUrl()}?key=in.(${keys.map(encodeURIComponent).join(",")})&select=value`,
    { headers: headers() },
  );
  if (!res.ok) throw new Error(`mget failed (${res.status}): ${await res.text()}`);
  return (await res.json()).map((d: any) => d.value);
};

export const mdel = async (keys: string[]): Promise<void> => {
  const res = await fetch(
    `${getUrl()}?key=in.(${keys.map(encodeURIComponent).join(",")})`,
    { method: "DELETE", headers: headers() },
  );
  if (!res.ok) throw new Error(`mdel failed (${res.status}): ${await res.text()}`);
};

export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const res = await fetch(
    `${getUrl()}?key=like.${encodeURIComponent(prefix + "%")}&select=value`,
    { headers: headers() },
  );
  if (!res.ok) throw new Error(`getByPrefix failed (${res.status}): ${await res.text()}`);
  return (await res.json()).map((d: any) => d.value);
};
